name: Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Deploy
    strategy:
      matrix:
        app: [pairs_one]
        env: [staging]
        os: [ubuntu-latest]
        otp: [24.3.4.8]
        elixir: [1.13.4]
        node: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    # https://sirfitz.medium.com/install-elm-0-18-0-in-2021-3f64ce298801
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get --only prod
        yarn --cwd assets install
        curl -L -o elm.tar.gz https://github.com/lydell/elm-old-binaries/releases/download/main/0.18.0-linux-x64.tar.gz
        tar -xzf elm.tar.gz
        chmod +x dist_binaries/*
        mv dist_binaries/* /usr/local/bin/

    - name: Prepare release
      run: |
        mix compile --warnings-as-errors
        yarn --cwd assets deploy
        mix phx.digest
        mix release
        tar -cjf release.tar.bz2 _build/staging
      env:
        MIX_ENV: staging
        REDIS_URI: ${{ secrets.REDIS_URI }}
        RELEASE_COOKIE: ${{ secrets.RELEASE_COOKIE }}
        SECRET_KEY_BASE: ${{secrets.SECRET_KEY_BASE}}
        SENTRY_DSN: ${{secrets.SENTRY_DSN}}

    - name: Upload release to all hosts
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.DEPLOYMENT_KEY }}
        username: deploy
        host: "46.101.106.59,161.35.200.233"
        source: release.tar.bz2
        target: ${{ matrix.app }}_${{matrix.env}}

    # For these to work, add to /etc/sudoers:
    # deploy ALL=(ALL) NOPASSWD: /bin/systemctl start pairs_one_staging
    # deploy ALL=(ALL) NOPASSWD: /bin/systemctl stop pairs_one_staging

    - name: Unpack and restart release on do1
      uses: appleboy/ssh-action@master
      with:
        host: "46.101.106.59"
        username: deploy
        key: ${{ secrets.DEPLOYMENT_KEY }}
        script_stop: true
        script: |
          sudo systemctl stop pairs_one_staging
          cd ${{matrix.app}}_${{matrix.env}}
          folder=`date '+%Y-%m-%d-%H-%M'`
          mkdir $folder
          ln -sfn `readlink -f current` old
          ln -sfn `readlink -f $folder` current
          tar -xjf release.tar.bz2 -C current
          sudo systemctl start pairs_one_staging

    - name: Give it 30 seconds to start...
      run: sleep 30

    - name: Unpack and restart release on do2
      uses: appleboy/ssh-action@master
      with:
        host: "161.35.200.233"
        username: deploy
        key: ${{ secrets.DEPLOYMENT_KEY }}
        script_stop: true
        script: |
          sudo systemctl stop pairs_one_staging
          cd ${{matrix.app}}_${{matrix.env}}
          folder=`date '+%Y-%m-%d-%H-%M'`
          mkdir $folder
          ln -sfn `readlink -f current` old
          ln -sfn `readlink -f $folder` current
          tar -xjf release.tar.bz2 -C current
          sudo systemctl start pairs_one_staging

